# Generated by Django 4.2.9 on 2025-07-02 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_xml', models.FileField(upload_to='nfe/xml/')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='nfe/pdf/')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PENDENTE', max_length=20)),
                ('cfop', models.CharField(blank=True, max_length=10)),
                ('ncm', models.CharField(blank=True, max_length=10)),
                ('cst', models.CharField(blank=True, max_length=10)),
                ('icms', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('classificacao', models.CharField(blank=True, max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa')),
            ],
        ),
    ]
